name: bastion_ordering
description: Ordering page for test

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  flutter_svg: 0.19.1
  latlong: 0.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
flutter:
  uses-material-design: true

  assets:
    - assets/common/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 700


